//
//  PouchLog+Can.swift
//  nicnark-2
//
//  PouchLog extension for Can relationship in v2.0
//

import Foundation
import CoreData

extension PouchLog {
    // The can property is now auto-generated by Core Data in PouchLog+CoreDataProperties.swift
}
